name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-CacheServer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./CacheServer/CacheServer.csproj
    - name: Build Client
      run: dotnet build --no-restore ./CacheServer/CacheServer.csproj
    - name: Test Client
      run: dotnet test --no-build --verbosity normal ./CacheServer/CacheServer.csproj

  build-CartridgeServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./CartridgeServer/CartridgeServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore ./CartridgeServer/CartridgeServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal ./CartridgeServer/CartridgeServer.csproj

  build-ChatServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./ChatServer/ChatServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore ./ChatServer/ChatServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal ./ChatServer/ChatServer.csproj

  build-ClientApiServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./ClientApiServer/ClientApiServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore ./ClientApiServer/ClientApiServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal ./ClientApiServer/ClientApiServer.csproj

  build-GameApiServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./GameApiServer/GameApiServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore ./GameApiServer/GameApiServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal ./GameApiServer/GameApiServer.csproj

  build-GameServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move to Client
      run: cd GameServer
    - name: Restore dependencies
      run: dotnet restore ./GameServer/GameServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore ./GameServer/GameServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal ./GameServer/GameServer.csproj
