name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move to Client
      run: cd ClientServer
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Client
      run: dotnet build --no-restore
    - name: Test Client
      run: dotnet test --no-build --verbosity normal
  build-game:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move to Client
      run: cd GameServer
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Game Server
      run: dotnet build --no-restore
    - name: Test Game Server
      run: dotnet test --no-build --verbosity normal
