name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-CacheServer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move to Client
      run: pwd
    - name: Move to Client
      run: cd CacheServer
    - name: Restore dependencies
      run: dotnet restore ./CacheServer/CacheServer.csproj
    - name: Build Client
      run: dotnet build --no-restore CacheServer.csproj
    - name: Test Client
      run: dotnet test --no-build --verbosity normal CacheServer.csproj

  build-CartridgeServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move to Client
      run: cd CartridgeServer
    - name: Restore dependencies
      run: dotnet restore CartridgeServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore CartridgeServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal CartridgeServer.csproj

  build-ChatServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move to Client
      run: cd ChatServer
    - name: Restore dependencies
      run: dotnet restore ChatServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore ChatServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal ChatServer.csproj

  build-ClientApiServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move to Client
      run: cd ClientApiServer
    - name: Restore dependencies
      run: dotnet restore ClientApiServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore ClientApiServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal ClientApiServer.csproj

  build-GameApiServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move to Client
      run: cd GameApiServer
    - name: Restore dependencies
      run: dotnet restore GameApiServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore GameApiServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal GameApiServer.csproj

  build-GameServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move to Client
      run: cd GameServer
    - name: Restore dependencies
      run: dotnet restore GameServer.csproj
    - name: Build Cartridge Server
      run: dotnet build --no-restore GameServer.csproj
    - name: Test Cartridge Server
      run: dotnet test --no-build --verbosity normal GameServer.csproj
